name: ce-connector-template
jobs:
  - name: build-{{.PR}}
    node: build
    triggers:
      githubHook: true
    bindings:
      - type: string
        credentialID: DOCKER_PASSWORD
        variable: DOCKER_PASSWORD
    commands:
      - docker login -u lokalise -p ${DOCKER_PASSWORD} reg.lokalise.work
      - docker build -t reg.lokalise.work/content-engine/ce-connector-template:PRE-{{.PR}} .
      - docker push reg.lokalise.work/content-engine/ce-connector-template:PRE-{{.PR}}

  - name: deploy-{{.PR}}
    node: template-{{.PR}}
    triggers:
      upstream: build-{{.PR}}
    bindings:
      - type: string
        credentialID: DOCKER_PASSWORD
        variable: DOCKER_PASSWORD
    commands:
      - cp .env.example .env
      - docker login -u lokalise -p ${DOCKER_PASSWORD} reg.lokalise.work
      - TAG=PRE-{{.PR}} docker-compose -f docker-compose-pre.yml pull
      - TAG=PRE-{{.PR}} docker-compose -f docker-compose-pre.yml up -d
